### ISSUE TITLE
您好，今天Fork了您的项目，但发现部署以后打不开。

### ISSUE THREAD

**Issue by Rob8it** [jjdxmashl/jjdxm_pililive#5]
您好，今天Fork了您的项目，但发现部署以后打不开。
具体报错如下：貌似是添加依赖的库出错了

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.dou361.live-1/lib/arm/libhyphenate_av.so" has unexpected e_machine: 40
                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                     at java.lang.System.loadLibrary(System.java:988)
                                                                     at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source)
                                                                     at com.hyphenate.chat.EMClient.getInstance(Unknown Source)
                                                                     at com.hyphenate.easeui.controller.EaseUI.init(EaseUI.java:113)
                                                                     at com.dou361.live.ui.application.BaseApplication.onCreate(BaseApplication.java:36)
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jjdxmashl** [comment]
ABI配置了过滤，只兼容部分设备，需要把app中的build.gradle文件中的ndk过滤去掉并补全ABI的类型

**Comment by Rob8it** [comment]
解决了，谢谢大神
